import {assert,createSimulation,WAREHOUSE_LAYOUT,runScenario} from './simulation-harness.mjs';
const sim=createSimulation(WAREHOUSE_LAYOUT,7);sim.dispatch({type:'START_SCENARIO',scenarioId:'junction'});for(let i=0;i<180;i++)sim.step(1/60);
const moving=sim.snapshot();sim.dispatch({type:'PAUSE'});for(let i=0;i<600;i++)sim.step(1/60);let s=sim.snapshot();assert(s.metrics.simTime===moving.metrics.simTime&&JSON.stringify(s.robots)===JSON.stringify(moving.robots),'Pause mutated state');sim.dispatch({type:'PLAY'});sim.step(1/60);assert(sim.snapshot().metrics.simTime>moving.metrics.simTime,'Resume failed');
sim.dispatch({type:'STOP'});const stopped=sim.snapshot();sim.step(1);assert(sim.snapshot().metrics.simTime===stopped.metrics.simTime,'Stop lost retained state');sim.dispatch({type:'PLAY'});s=sim.snapshot();assert(s.generation>stopped.generation&&s.metrics.simTime===0,'Play after Stop not fresh');
for(let i=0;i<5;i++){const before=sim.snapshot();sim.dispatch({type:'RESET'});s=sim.snapshot();assert(s.generation===before.generation+1&&s.metricHistory.length===0&&s.metrics.simTime===0,'Reset generation/history');sim.dispatch({type:'START_SCENARIO',scenarioId:i%2?'narrow':'junction'});assert(sim.snapshot().simulationStatus==='RUNNING','Scenario not auto-play');}
const a=createSimulation(WAREHOUSE_LAYOUT,42),b=createSimulation(WAREHOUSE_LAYOUT,42);for(const q of [a,b])q.dispatch({type:'START_SCENARIO',scenarioId:'network'});for(let i=0;i<1200;i++){a.step(1/60);b.step(1/60);}assert(JSON.stringify(a.snapshot())===JSON.stringify(b.snapshot()),'Nondeterministic seeded run');
for(const id of ['robot-failure','payload-recovery','blocked-aisle','charging']){
 let custodyObserved=false;const result=runScenario(id,300,1/60,(q,state)=>{if(id==='payload-recovery'&&state.robots.R01.failed){const r=state.robots.R01,t=state.tasks[r.taskId];assert(r.payload&&t.status==='RECOVERY_REQUIRED'&&t.custodyRobotId==='R01','Payload custody lost');custodyObserved=true;if(state.metrics.simTime>8)q.dispatch({type:'RECOVER_ROBOT',robotId:'R01'});}});
 assert(result.scenarioProgress.completed,id+' outcome missing');assert(result.metrics.overlapViolations===0,id+' overlap');if(id==='payload-recovery')assert(custodyObserved,'Failed payload not observed');if(id==='robot-failure')assert(result.events.some(e=>e.kind==='REASSIGN'),'No reassignment');console.log('RUNTIME_PASS',id,result.metrics.simTime.toFixed(2));
}
const delayed=createSimulation(WAREHOUSE_LAYOUT,12345);delayed.dispatch({type:'START_SCENARIO',scenarioId:'network'});for(let i=0;i<480;i++){delayed.step(1/60);if(i>=60&&i<300&&i%10===0)delayed.dispatch({type:i%20?'ENABLE_JEC':'DISABLE_JEC',jecId:'JEC-1'});}assert(delayed.snapshot().events.some(e=>e.kind==='STALE_GRANT'),'No old-authority grant rejection');
console.log('RUNTIME_VERIFICATION_OK: lifecycle, generation, pause/stop/reset, seeds, custody, blockage and stale grants');
// Regression evidence beyond scenario pass flags.
const delivered=createSimulation(WAREHOUSE_LAYOUT);delivered.dispatch({type:'START_SCENARIO',scenarioId:'junction'});let deliveredRobot;for(let i=0;i<3000&&!deliveredRobot;i++){delivered.step(1/60);const state=delivered.snapshot();deliveredRobot=Object.values(state.robots).find(r=>r.state==='RETURNING_TO_STAGING'&&r.taskId&&state.tasks[r.taskId].status==='COMPLETED');}assert(deliveredRobot,'No completed-returning fixture');let beforeFailure=delivered.snapshot();delivered.dispatch({type:'FAIL_ROBOT',robotId:deliveredRobot.id});let afterFailure=delivered.snapshot();assert(afterFailure.metrics.tasksCompleted===beforeFailure.metrics.tasksCompleted,'Failure requeued completed delivery');assert(Object.values(afterFailure.tasks).filter(t=>t.status==='QUEUED').length===0,'Delivered task duplicated');
const unreachable=createSimulation(WAREHOUSE_LAYOUT);unreachable.dispatch({type:'START_SCENARIO',scenarioId:'robot-failure'});const service='B3_LEFT_SERVICE',sealed=WAREHOUSE_LAYOUT.graph.nodes[service].neighbors.map(n=>[service,n].sort().join('|'));for(const resourceId of sealed)unreachable.dispatch({type:'BLOCK_AISLE',resourceId});for(let i=0;i<60;i++)unreachable.step(1/60);let unreachableState=unreachable.snapshot();const held=Object.values(unreachableState.robots).find(r=>r.waitReason==='No clear route');assert(held&&held.route.length===0&&held.eta===null,'No-route route/ETA stale');for(const resourceId of sealed)unreachable.dispatch({type:'CLEAR_AISLE',resourceId});unreachableState=unreachable.snapshot();assert(unreachableState.robots[held.id].route.length>0,'No-route did not recover after clearing');
const chargeResult=runScenario('charging',300);assert(chargeResult.robots.R03.failed&&chargeResult.robots.R03.battery===0,'Depletion did not stop robot');assert(['R01','R02'].every(id=>chargeResult.robots[id].state==='IDLE'&&chargeResult.events.some(e=>e.kind==='CHARGED'&&e.robotId===id)),'Both chargers must reach charge threshold and return');
console.log('ADVERSARIAL_RUNTIME_OK: completed-task failure, no-route/clear, depletion and both charging returns');
const narrowBlock=createSimulation(WAREHOUSE_LAYOUT);narrowBlock.dispatch({type:'START_SCENARIO',scenarioId:'narrow'});for(let i=0;i<120;i++)narrowBlock.step(1/60);narrowBlock.dispatch({type:'BLOCK_AISLE',resourceId:'NARROW_1'});for(let i=0;i<60*120;i++){narrowBlock.step(1/60);if(i%6===0){const s=narrowBlock.snapshot();assert(!Object.values(s.robots).some(r=>r.position.x>6.4&&r.position.x<9.6&&Math.abs(r.position.y-23)<.7),'Forced fixture crossed blocked narrow passage');}}assert(narrowBlock.snapshot().metrics.tasksCompleted===2,'Valid blocked-narrow detour did not complete');console.log('BLOCKED_NARROW_REGRESSION_OK');
const guide=createSimulation(WAREHOUSE_LAYOUT,12345);guide.dispatch({type:'START_SCENARIO',scenarioId:'guided'});let guideState=guide.snapshot(),guideSteps=0;for(;guideSteps<60*2400;guideSteps++){guide.step(1/60);if(guideSteps%60===0){guideState=guide.snapshot();assert(!guideState.scenarioProgress.timedOut,'Guided stage timed out: '+guideState.scenarioProgress.detail);assert(guideState.metrics.overlapViolations===0,'Guided footprint overlap');if(guideState.scenarioProgress.completed)break;}}guideState=guide.snapshot();assert(guideState.scenarioProgress.completed,'Guided did not finish');const expected=['junction','narrow','following','detour','fairness','deadlock','jec-outage','robot-failure','payload-recovery','blocked-aisle','network','charging','logistics'];assert(JSON.stringify(guideState.scenarioResults.map(r=>r.id))===JSON.stringify(expected),'Guided results missing/reordered');assert(guideState.scenarioResults.every(r=>r.passed&&!r.timedOut&&r.overlapViolations===0),'Guided false success');assert(guideState.scenarioResults.at(-1).tasksCompleted===20,'Guided fleet incomplete');console.log('GUIDED_VERIFICATION_OK: 13 event-verified saved outcomes; '+(guideSteps/60).toFixed(2)+' total simulated seconds');guide.dispatch({type:'RESET'});assert(guide.snapshot().scenarioResults.length===0,'External reset did not clear guided history');
const resumedMotion=createSimulation(WAREHOUSE_LAYOUT);resumedMotion.dispatch({type:'START_SCENARIO',scenarioId:'payload-recovery'});let oldPose=resumedMotion.snapshot(),oldSpeed=0,recovered=false;for(let i=0;i<60*120;i++){resumedMotion.step(1/60);let state=resumedMotion.snapshot(),r=state.robots.R01;const speed=Math.hypot(r.position.x-oldPose.robots.R01.position.x,r.position.y-oldPose.robots.R01.position.y)*60;if(!r.failed&&!oldPose.robots.R01.failed){const acceleration=(speed-oldSpeed)*60;assert(acceleration>=-.87&&acceleration<=.77,'Recovered payload U-turn pose acceleration '+acceleration);}oldSpeed=speed;oldPose=state;if(r.failed&&state.metrics.simTime>8&&!recovered){resumedMotion.dispatch({type:'RECOVER_ROBOT',robotId:'R01'});oldPose=resumedMotion.snapshot();oldSpeed=0;recovered=true;}if(state.scenarioProgress.completed)break;}assert(recovered&&oldPose.scenarioProgress.completed,'Payload motion/recovery outcome missing');console.log('PAYLOAD_PIVOT_MOTION_OK: explicit operator recovery, bounded actual pose speed through true U-turn');
